//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rapid.Tools.SPDeploy.AddIn.Resources.Features.WebParts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rapid.Tools.SPDeploy.AddIn.Resources.Features.WebParts.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Microsoft.SharePoint;
        ///using Microsoft.SharePoint.Administration;
        ///
        ///namespace Ajaxification
        ///{
        ///    public class FeatureReceiver : SPFeatureReceiver
        ///    {
        ///
        ///        public override void FeatureInstalled(SPFeatureReceiverProperties properties) { }
        ///        public override void FeatureUninstalling(SPFeatureReceiverProperties properties) { }
        ///
        ///        public override void FeatureActivated(SPFeatureReceiverProperties properties)
        ///        {
        ///            SPWebApplication WebApp = (SPWebAp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ajaxification {
            get {
                return ResourceManager.GetString("Ajaxification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Web;
        ///using System.Web.UI;
        ///using System.Web.UI.WebControls;
        ///using System.Web.UI.WebControls.WebParts;
        ///using Microsoft.SharePoint;
        ///
        ///namespace [REPLACEPROJECTNAME].Web.UI.WebControls
        ///{
        ///    public class [REPLACEWEBPARTFILENAME] : WebPart
        ///    {
        ///
        ///        private ScriptManager scriptMan;
        ///        public ScriptManager CurrentScriptManager
        ///        {
        ///            get
        ///            {
        ///                if (scriptMan == null)
        ///                {
        ///                    scriptMan = Scrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AjaxWebPart {
            get {
                return ResourceManager.GetString("AjaxWebPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Elements xmlns=&quot;http://schemas.microsoft.com/sharepoint/&quot;&gt;
        ///	&lt;Module Url=&quot;_catalogs/wp&quot;
        ///            RootWebOnly=&quot;TRUE&quot;&gt;    
        ///    &lt;File Url=&quot;[REPLACEWEBPARTFILENAME].webpart&quot;
        ///			  Type=&quot;GhostableInLibrary&quot;&gt;
        ///      &lt;Property Name=&quot;Group&quot; Value=&quot;[REPLACEPROJECTNAME]&quot; /&gt;
        ///      &lt;Property Name=&quot;Title&quot; Value=&quot;[REPLACEWEBPARTTITLE]&quot; /&gt;
        ///    &lt;/File&gt;   
        ///	&lt;/Module&gt;
        ///&lt;/Elements&gt;.
        /// </summary>
        internal static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Feature xmlns=&quot;http://schemas.microsoft.com/sharepoint/&quot;
        ///		 Id=&quot;[REPLACEGUID]&quot;
        ///		 Title=&quot;[REPLACEFEATURETITLE]&quot;
        ///		 Description =&quot;[REPLACEFEATUREDESCRIPTION]&quot; 
        ///		 Hidden=&quot;FALSE&quot;
        ///		 Scope=&quot;Site&quot;
        ///		 Version=&quot;1.0.0.0&quot;     
        ///     &gt;
        ///
        ///	&lt;ElementManifests&gt;
        ///		&lt;ElementManifest Location=&quot;elements.xml&quot; /&gt;
        ///  &lt;/ElementManifests&gt;
        ///	
        ///&lt;/Feature&gt;.
        /// </summary>
        internal static string feature {
            get {
                return ResourceManager.GetString("feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function CallWebService() {  
        ///    [REPLACEPROJECTNAME].HelloWebService.set_path(window.wsUrl);
        ///    [REPLACEPROJECTNAME].HelloWebService.HelloWorld(WebServiceCallback);
        ///}
        ///  
        ///function WebServiceCallback(result) {
        ///    var display = document.getElementById(&quot;DisplaySpan&quot;);
        ///    display.innerHTML = result;
        ///}.
        /// </summary>
        internal static string HelloScript {
            get {
                return ResourceManager.GetString("HelloScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ WebService Language=&quot;C#&quot; Class=&quot;[REPLACEPROJECTNAME].HelloWebService, [REPLACEPROJECTNAME], Version=1.0.0.0, Culture=neutral, PublicKeyToken=4623235946e3a5b5&quot;%&gt;
        ///.
        /// </summary>
        internal static string HelloWebService {
            get {
                return ResourceManager.GetString("HelloWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Web.Services;
        ///using System.Web.Script.Services;
        ///using Microsoft.SharePoint;
        ///using System.Security.Permissions;
        ///
        ///namespace [REPLACEPROJECTNAME]
        ///{
        ///    // An example callback Web Service API for the Hello2 Web Part
        ///    [WebService(Namespace = &quot;http://[REPLACEMACHINENAME]/[REPLACEPROJECTNAME]&quot;)]
        ///    [WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]
        ///    [ScriptService]
        ///    public class HelloWebService : Syst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelloWebService1 {
            get {
                return ResourceManager.GetString("HelloWebService1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Web.UI;
        ///
        ///[assembly: WebResource(@&quot;[REPLACEPROJECTNAME].Web.UI.WebControls.WebPartResources.HelloScript.js&quot;, @&quot;text/javascript&quot;)]
        ///
        ///.
        /// </summary>
        internal static string ResourceDeclarations {
            get {
                return ResourceManager.GetString("ResourceDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Web;
        ///using System.Web.UI;
        ///using System.Web.UI.WebControls;
        ///using System.Web.UI.WebControls.WebParts;
        ///
        ///namespace [REPLACEPROJECTNAME].Web.UI.WebControls
        ///{
        ///    public class [REPLACEWEBPARTFILENAME] : WebPart
        ///    {
        ///        protected override void OnInit(EventArgs e)
        ///        {
        ///            base.OnInit(e);
        ///        }
        ///
        ///        protected override void CreateChildControls()
        ///        {
        ///            base.CreateChildControls();
        ///        }
        ///
        ///        protected override void OnPre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string webpartclass {
            get {
                return ResourceManager.GetString("webpartclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;webParts&gt;
        ///  &lt;webPart xmlns=&quot;http://schemas.microsoft.com/WebPart/v3&quot;&gt;
        ///    &lt;metaData&gt;
        ///      &lt;type name=&quot;[REPLACEPROJECTNAME].Web.UI.WebControls.[REPLACEWEBPARTFILENAME], [REPLACEPROJECTNAME], Version=1.0.0.0, Culture=neutral, PublicKeyToken=4623235946e3a5b5&quot; /&gt;
        ///      &lt;importErrorMessage&gt;Error importing the Web Part.&lt;/importErrorMessage&gt;
        ///    &lt;/metaData&gt;
        ///    &lt;data&gt;
        ///      &lt;properties&gt;
        ///        &lt;property name=&quot;Title&quot; type=&quot;string&quot;&gt;[REPLACEWEBPARTTITLE]&lt;/property&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string webpartdotwebpart {
            get {
                return ResourceManager.GetString("webpartdotwebpart", resourceCulture);
            }
        }
    }
}
